language: python
sudo: false
python:
    - 2.7
install:
    # We have to upgrade pytest explicitly here due to the following:
    # * Travis CI's virtualenv already comes with pytest preinstalled.
    # * pytest-flake8 requires pytest>=2.8, and sometimes this requirement is
    #   higher than what Travis CI has pre-installed into the virtualenv.
    # * 'python setup.py test' uses EasyInstall, so it will not upgrade a
    #   package to a newer version if the package is already present in a
    #   virtualenv.
  - pip install pytest-flake8
  - pip install pytest-cov python-coveralls
script:
  - python setup.py test -v -a "--cov-config .coveragerc --cov=errata_tool"
after_success:
  - coveralls

cache:
  directories:
  - $HOME/.cache/pip
